file_format: "1"
id: cygnus
name: Cygnus
type: shield
url:
requires:
  - pro_micro
features:
  - keys
  - pointing_device
outputs:
  - usb
  - ble
siblings:
  - cygnus_central_dongle
  - cygnus_peripheral_left
  - cygnus_peripheral_right
